title: "Chenxiao's Personal Website"
theme: minima

minima:
  navigation:
    - name: "Home"
      url: /
    - name: "About"
      url: /about/
    - name: "Publication"
      url: /publication/
    - name: "CV"
      url: /cv/
